name: cat_charity_fund

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip 
          pip install flake8 pep8-naming flake8-broken-line flake8-return
          pip install -r requirements.txt
   
      - name: Test with flake8 and run practicum tests
        run: |
          python -m flake8
          echo APP_TITLE=${{ secrets.APP_TITLE }} >> .env
          echo APP_AUTHOR=${{ secrets.APP_AUTHOR }} >> .env
          echo DESCRIPTION=${{ secrets.DESCRIPTION }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo SECRET=${{ secrets.SECRET }} >> .env
          echo FIRST_SUPERUSER_EMAIL=${{ secrets.FIRST_SUPERUSER_EMAIL }} >> .env
          echo FIRST_SUPERUSER_PASSWORD=${{ secrets.FIRST_SUPERUSER_PASSWORD }} >> .env
          pytest

  send_message:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }}/${{ github.ref }} успешно выполнен!
